#cloud-config
users:
  - default
  - name: opsuser01
    sudo: False
    lock_passwd: True
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWW+ApJHtkrjHZJrgW2bqOK7bgUhfWm3D8VEQjBBfhzDBwHWaQM3ld8sM6+qW5vFWVbxWHTB31X0s6yFkIKtx0whSAw8rnFp80iP3vQ2cDh7/2VyZ3vBo036jxw5zzpDRfsa3sw776dS3n670TpuBV/Ne5+HHmJ+LvjPp7M/EsMWu7FkFTsDhK/7aJj1xKelkq6kcSA5OzYMjJrCReZ9NmOKB1fFB4qQK2+p+BomPG4r/FdpRUAM1snt8/W4bgHZh503ReP23Xajk9k9wCzNWb/Z9xvVHP+tboxFpU0SQZJ2Gou8lvAMNPCAI8sK3XbSDz5/v9ox/C6FvYBWX07WQNvsvNkmbKioHDh/o6FRh/1jg51n6Yp8IcHAayOnCihKiwDFXUDETbXYpZtnAyt93Ws+nFMoP9TdsIHE0myGvFUefs1hVkmDGKqEcj9Z1ZnrRceL+iVnehEJDHFViQXjyL6mJv6FyJGEGw3BIbLfUMvaMY+CRz7iA7DO350ThQdcdcatzH57W2KX9W2cQx+KKgoJkBy3aj1LhfCL06Li88uPklLpbFyxJK3KgedVMR/jSSyMhQdYRJqr8tSgn+tgh91JYUaRogHNYzj9fPSz6aGXEy+Dd6njOzSYrM0sS93NlBH3824NAyxKMtGrrLE1JS7EUjXROHy7Sj2YeQd6yH7Q== codespace@codespaces_3d9d93